CREATE TABLE TIPO_EXECUCAO
(
	COD_TIP_EXECUCAO 		TINYINT NOT NULL AUTO_INCREMENT,
    DES_TIP_EXECUCAO		VARCHAR(100) NOT NULL,
    PRIMARY KEY (COD_TIP_EXECUCAO)
);

CREATE TABLE EXPERIMENTO
(
	NUM_EXECUCAO	 		INT NOT NULL AUTO_INCREMENT,
    COD_TIP_EXECUCAO		TINYINT NOT NULL,
    NUM_PROCESSOS_THREADS	TINYINT NOT NULL,
    VAL_TEMPO_EXECUCAO		DOUBLE NOT NULL,
    PRIMARY KEY (NUM_EXECUCAO),
    FOREIGN KEY (COD_TIP_EXECUCAO) REFERENCES TIPO_EXECUCAO (COD_TIP_EXECUCAO)
)

